functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность регистрации на сайте
  - Пользователь должен иметь возможность авторизации на сайте
  - Пользователь должен иметь возможность заполнения формы для оплаты товара
  - Пользователь должен иметь возможность выбора доставки
  - Сайт должен быть адаптивным к русскому и английскому языку с возможностью выбора языка
  - Цены на товар должны быть в долларах
  
